on:
  workflow_call:
    secrets:
      build_secrets:
        required: false
      github_pat:
        required: true
    inputs:
      deploy:
        type: boolean
        default: true
      dockerfile:
        type: string
        default: Dockerfile
        required: false
      build_args:
        type: string
        description: "Builds args passed to docker build"
        required: false
      repository:
        type: string
        description: "GitHub repository containing the kustomization"
        default: atb-as/gcp-infra
      overlays_base:
        type: string
        description: "Base path to directory holding kustomization overlays"
        default: manifests/amp/platform
      ref:
        type: string
        description: "ref to push changes to"
        default: main
      release_overlay:
        type: string
        description: "Overlay(s) to edit on GitHub `release` event"
        default: prod
      push_overlay:
        type: string
        description: "Overlay(s) to edit on GitHub `push` event"
        default: staging
      image:
        type: string
        description: "Full path to the image (gcr.io/my/image)"
        required: true
      workload_identity_provider:
        type: string
        description: "Workload identity federation provider"
        required: false
        default: "projects/827196677776/locations/global/workloadIdentityPools/ci-builds/providers/github"
      workload_identity_service_account_email:
        type: string
        description: "IAM service account to generate credentials for"
        required: false
        default: "sa-gh-gcr-writer@atb-mobility-platform.iam.gserviceaccount.com"

jobs:
  bump_infra_prod:
    if: inputs.deploy && github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          token: ${{ secrets.github_pat }}
      - uses: imranismail/setup-kustomize@v2
      - env:
          OVERLAY: ${{ inputs.release_overlay }}
        run: |
          TAG=`echo -e "${{ needs.build.outputs.tags }}" | head -1`
          for o in $OVERLAY
          do
            ( cd ${{ inputs.overlays_base }}/$o && \
              kustomize edit set image ${{ inputs.image }}=$TAG )
          done
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[ci] prod: bump ${{ inputs.image }} image'
          branch: ${{ inputs.ref }}
  bump_infra_staging:
    if: inputs.deploy && github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          token: ${{ secrets.github_pat }}
      - uses: imranismail/setup-kustomize@v2
      - env:
          OVERLAY: ${{ inputs.push_overlay }}
        run: |
          TAG=`echo -e "${{ needs.build.outputs.tags }}" | head -1`
          for o in $OVERLAY
          do
            ( cd ${{ inputs.overlays_base }}/$o && \
              kustomize edit set image ${{ inputs.image }}=$TAG )
          done
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[ci] staging: bump ${{ inputs.image }} image'
          branch: ${{ inputs.ref }}
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      - id: buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image }}
          tags: |
            type=semver,pattern={{raw}},priority=900
            type=sha,prefix=,enable=true,format=short,priority=800
            type=raw,value=latest,enable={{is_default_branch}},priority=100
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.workload_identity_service_account_email }}
      - id: ignore-auth-credentials
        run: |
          echo ${GOOGLE_GHA_CREDS_PATH} | tee -a .dockerignore .gitignore
      - id: gcr
        name: Configure docker for GCR
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - id: buildpush
        name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: ${{ inputs.dockerfile }}
          build-args: ${{ inputs.build_args }}
          secrets: ${{ secrets.build_secrets }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha,scope=${{ inputs.image }}
          cache-to: type=gha,mode=max,scope=${{ inputs.image }}
