on:
  workflow_call:
    secrets:
      build_secrets:
        required: false
    inputs:
      build_args:
        type: string
        description: "Builds args passed to docker build"
        required: false
      gcr_token:
        type: string
        description: "Container Registry access token"
        required: true
      tags:
        type: string
        description: "Comma separated list of tags to apply to the built container"
        required: true
      image:
        type: string
        description: "Full path to the image (gcr.io/my/image)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - id: gcr
        name: Configure docker for GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ inputs.gcr_token }}
      - id: buildpush
        name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile
          build-args: ${{ inputs.build_args }}
          secrets: ${{ secrets.build_secrets }}
          push: true
          tags: ${{ inputs.tags }}
          cache-from: type=gha,scope=${{ inputs.image }}
          cache-to: type=gha,mode=max,scope=${{ inputs.image }}
