on:
  workflow_call:
    inputs:
      workload_identity_provider:
        type: string
        description: "Workload identity federation provider"
        required: false
        default: "projects/939812594010/locations/global/workloadIdentityPools/ci-builds/providers/github"
      workload_identity_service_account_email:
        type: string
        description: "IAM service account to generate credentials for"
        required: false
        default: "sa-gh-gcr-writer@atb-mobility-platform-staging.iam.gserviceaccount.com"
    outputs:
      access_token: ${{ jobs.auth.outputs.access_token }}
jobs:
  auth:
    runs-on: ubuntu-latest
    outputs:
      access_token: ${{ steps.auth.outputs.access_token }}
    steps:
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.workload_identity_service_account_email }}
