on:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/docker-build-push.yaml
    with:
      image: gcr.io/atb-mobility-platform/foo
